services:
  database:
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    build:
      dockerfile: src/KANJI.DATABASE/Dockerfile
    ports:
      - 5432:5432

  service:
    build:
      context: ./src/KANJI.SERVICE
      dockerfile: Dockerfile
    ports:
      - 5059:8080
      # - 7012:443 SSL later onn
    # environment:
    #   - "ConnectionStrings:LearningAnalyticsAPIContext=Server=db;Port=4000;Database=LearningAnalytics;User=root;SslMode=None;ConnectionReset=false;connect timeout=3600"     
    depends_on:
      - database
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080